version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        PORT: 3001
        REACT_APP_API_URL: "http://localhost:3000"
    ports:
      - '80:80'
    depends_on:
      - backend
